about 800000

diff --git a/etc/init.d/nginx b/etc/init.d/nginx
--- a/etc/init.d/nginx
+++ b/etc/init.d/nginx
@@ -1,196 +1,177 @@
 #!/bin/sh
-
 ### BEGIN INIT INFO
-# Provides:	  nginx
-# Required-Start:    $local_fs $remote_fs $network $syslog $named
-# Required-Stop:     $local_fs $remote_fs $network $syslog $named
+# Provides:          nginx
+# Required-Start:    $network $remote_fs $local_fs 
+# Required-Stop:     $network $remote_fs $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the nginx web server
-# Description:       starts nginx using start-stop-daemon
+# Short-Description: Stop/start nginx
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/nginx
-NAME=nginx
-DESC=nginx
+# Author: Sergey Budnevitch <sb@nginx.com>
 
-# Include nginx defaults if available
-if [ -r /etc/default/nginx ]; then
-	. /etc/default/nginx
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
+if [ -L $0 ]; then
+    SCRIPTNAME=`/bin/readlink -f $0`
+else
+    SCRIPTNAME=$0
 fi
 
-STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
+sysconfig=`/usr/bin/basename $SCRIPTNAME`
 
-test -x $DAEMON || exit 0
+[ -r /etc/default/$sysconfig ] && . /etc/default/$sysconfig
+
+DESC=${DESC:-nginx}
+NAME=${NAME:-nginx}
+CONFFILE=${CONFFILE:-/etc/nginx/nginx.conf}
+DAEMON=${DAEMON:-/usr/sbin/nginx}
+PIDFILE=${PIDFILE:-/var/run/nginx.pid}
+SLEEPSEC=${SLEEPSEC:-1}
+UPGRADEWAITLOOPS=${UPGRADEWAITLOOPS:-5}
+CHECKSLEEP=${CHECKSLEEP:-3}
+
+[ -x $DAEMON ] || exit 0
+
+DAEMON_ARGS="-c $CONFFILE $DAEMON_ARGS"
 
 . /lib/init/vars.sh
+
 . /lib/lsb/init-functions
 
-# Try to extract nginx pidfile
-PID=$(cat /etc/nginx/nginx.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
-if [ -z "$PID" ]; then
-	PID=/run/nginx.pid
-fi
-
-if [ -n "$ULIMIT" ]; then
-	# Set ulimit if it is set in /etc/default/nginx
-	ulimit $ULIMIT
-fi
-
-start_nginx() {
-	# Start the daemon/service
-	#
-	# Returns:
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-		$DAEMON_OPTS 2>/dev/null \
-		|| return 2
+do_start()
+{
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+        $DAEMON_ARGS
+    RETVAL="$?"
+    return "$RETVAL"
 }
 
-test_config() {
-	# Test the nginx configuration
-	$DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+    RETVAL="$?"
+    rm -f $PIDFILE
+    return "$RETVAL"
 }
 
-stop_nginx() {
-	# Stops the daemon/service
-	#
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
-	RETVAL="$?"
-	sleep 1
-	return "$RETVAL"
+do_reload() {
+    #
+    start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE
+    RETVAL="$?"
+    return "$RETVAL"
 }
 
-reload_nginx() {
-	# Function that sends a SIGHUP to the daemon/service
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
-	return 0
+do_configtest() {
+    if [ "$#" -ne 0 ]; then
+        case "$1" in
+            -q)
+                FLAG=$1
+                ;;
+            *)
+                ;;
+        esac
+        shift
+    fi
+    $DAEMON -t $FLAG -c $CONFFILE
+    RETVAL="$?"
+    return $RETVAL
 }
 
-rotate_logs() {
-	# Rotate log files
-	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
-	return 0
+do_upgrade() {
+    OLDBINPIDFILE=$PIDFILE.oldbin
+
+    do_configtest -q || return 6
+    start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE
+    RETVAL="$?"
+    
+    for i in `/usr/bin/seq  $UPGRADEWAITLOOPS`; do
+        sleep $SLEEPSEC
+        if [ -f $OLDBINPIDFILE -a -f $PIDFILE ]; then
+            start-stop-daemon --stop --signal QUIT --quiet --pidfile $OLDBINPIDFILE
+            RETVAL="$?"
+            return
+        fi
+    done
+
+    echo $"Upgrade failed!"
+    RETVAL=1
+    return $RETVAL
 }
 
-upgrade_nginx() {
-	# Online upgrade nginx executable
-	# http://nginx.org/en/docs/control.html
-	#
-	# Return
-	#   0 if nginx has been successfully upgraded
-	#   1 if nginx is not running
-	#   2 if the pid files were not created on time
-	#   3 if the old master could not be killed
-	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
-		# Wait for both old and new master to write their pid file
-		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
-			cnt=`expr $cnt + 1`
-			if [ $cnt -gt 10 ]; then
-				return 2
-			fi
-			sleep 1
-		done
-		# Everything is ready, gracefully stop the old master
-		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
-			return 0
-		else
-			return 3
-		fi
-	else
-		return 1
-	fi
+do_checkreload() {
+    templog=`/bin/mktemp --tmpdir nginx-check-reload-XXXXXX.log`
+    trap '/bin/rm -f $templog' 0
+    /usr/bin/tail --pid=$$ -n 0 --follow=name /var/log/nginx/error.log > $templog &
+    /bin/sleep 1
+    start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE
+    /bin/sleep $CHECKSLEEP
+    /bin/grep -E "\[emerg\]|\[alert\]" $templog
 }
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC" "$NAME"
-		start_nginx
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			2)   log_end_msg 1 ;;
-		esac
-		;;
-	stop)
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		stop_nginx
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			2)   log_end_msg 1 ;;
-		esac
-		;;
-	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-
-		# Check configuration before stopping nginx
-		if ! test_config; then
-			log_end_msg 1 # Configuration error
-			exit $?
-		fi
-
-		stop_nginx
-		case "$?" in
-			0|1)
-				start_nginx
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
-		;;
-	reload|force-reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
-
-		# Check configuration before stopping nginx
-		#
-		# This is not entirely correct since the on-disk nginx binary
-		# may differ from the in-memory one, but that's not common.
-		# We prefer to check the configuration and return an error
-		# to the administrator.
-		if ! test_config; then
-			log_end_msg 1 # Configuration error
-			exit $?
-		fi
-
-		reload_nginx
-		log_end_msg $?
-		;;
-	configtest|testconfig)
-		log_daemon_msg "Testing $DESC configuration"
-		test_config
-		log_end_msg $?
-		;;
-	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	upgrade)
-		log_daemon_msg "Upgrading binary" "$NAME"
-		upgrade_nginx
-		log_end_msg $?
-		;;
-	rotate)
-		log_daemon_msg "Re-opening $DESC log files" "$NAME"
-		rotate_logs
-		log_end_msg $?
-		;;
-	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
-		exit 3
-		;;
+    start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
+        do_start
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+  status)
+        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+  configtest)
+        do_configtest
+        ;;
+  upgrade)
+        do_upgrade
+        ;;
+  reload|force-reload)
+        log_daemon_msg "Reloading $DESC" "$NAME"
+        do_reload
+        log_end_msg $?
+        ;;
+  restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_configtest -q || exit $RETVAL
+        do_stop
+        case "$?" in
+            0|1)
+                do_start
+                case "$?" in
+                    0) log_end_msg 0 ;;
+                    1) log_end_msg 1 ;; # Old process is still running
+                    *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+            *)
+                # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
+        ;;
+    check-reload)
+        do_checkreload
+        RETVAL=0
+        ;;
+    *)
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload|upgrade|configtest|check-reload}" >&2
+        exit 3
+        ;;
 esac
+
+exit $RETVAL
